package vn.edu.tdtu.anhminh.myapplication.Data.Mapper;

import java.util.ArrayList;
import java.util.List;

import vn.edu.tdtu.anhminh.myapplication.Data.Local.Entity.InstructionEntity;
import vn.edu.tdtu.anhminh.myapplication.Data.Remote.DTO.InstructionDTO;
import vn.edu.tdtu.anhminh.myapplication.Domain.Model.Instruction;

public class InstructionMapper {
    private InstructionMapper(){
    }

    // DTO -> Entity
    public static InstructionEntity toEntity(InstructionDTO dto){
        if (dto == null) return null;

        InstructionEntity entity = new InstructionEntity();
        // ID is not set from DTO, will be auto-generated by Room
        entity.setRecipeId(dto.getRecipeId());
        entity.setStepNumber(dto.getStepNumber());
        entity.setInstruction(dto.getInstruction());
        return entity;
    }

    public static List<InstructionEntity> toEntityList(List<InstructionDTO> dtos) {
        if (dtos == null) return null;

        List<InstructionEntity> list = new ArrayList<>();
        for (InstructionDTO dto : dtos) {
            InstructionEntity entity = toEntity(dto);
            if (entity != null) {
                list.add(entity);
            }
        }
        return list;
    }

    // Entity -> Model
    public static Instruction toModel(InstructionEntity entity){
        if (entity == null) return null;

        Instruction model = new Instruction();
        model.setInstructionId(entity.getInstructionId());
        model.setRecipeId(entity.getRecipeId());
        model.setStepNumber(entity.getStepNumber());
        model.setInstruction(entity.getInstruction());
        return model;
    }

    public static List<Instruction> toModelList(List<InstructionEntity> entities) {
        if (entities == null) return null;

        List<Instruction> list = new ArrayList<>();
        for (InstructionEntity entity : entities) {
            Instruction model = toModel(entity);
            if (model != null) {
                list.add(model);
            }
        }
        return list;
    }

    // Model -> Entity
    public static InstructionEntity toEntity(Instruction model) {
        if (model == null) return null;

        InstructionEntity entity = new InstructionEntity();
        // ID is crucial for updates. If null, Room treats it as an insert.
        entity.setInstructionId(model.getInstructionId());
        entity.setRecipeId(model.getRecipeId());
        entity.setStepNumber(model.getStepNumber());
        entity.setInstruction(model.getInstruction());
        return entity;
    }
}
